#!/usr/bin/env python3
"""Derive the Cursor rule from the skill the Claude Code plugin ships.

One source of guidance for both clients, and a pure transform: Cursor's front matter replaces the
skill's, and the install section is dropped because it lives in the README where a reader meets it
once. Nothing else is rewritten.

Nothing else *should* be rewritten. Both clients read files of guidance, both speak streamable
HTTP, and both can fan work out across sub-agents — so an instruction that is right for one is
right for the other, and a second hand-maintained copy would only give the same product two
answers to the same question.

    python3 clients/cursor/generate.py
"""

from __future__ import annotations

import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[2]
SKILL = ROOT / "plugins/athena/skills/athena/SKILL.md"
RULE = ROOT / "clients/cursor/athena.mdc"

DESCRIPTION = (
    "Use the Engineering Athena handbook before planning or writing code. Call it when a feature, "
    "endpoint, model, migration, dependency choice or review is on the table, and when a standard "
    "or a house convention would change what you write."
)


def main() -> None:
    # Body after the skill's own front matter, minus the install steps.
    body = SKILL.read_text().split("---", 2)[2].lstrip("\n")
    body = body[: body.index("## Installing")].rstrip() + "\n"

    # `alwaysApply`, and no `globs`: a glob ties a rule to a file type, and whether to consult the
    # handbook is decided before anyone knows which files a change touches. It is as true of a
    # migration as of a Dockerfile.
    RULE.write_text(
        f"---\ndescription: {DESCRIPTION}\nalwaysApply: true\n---\n\n"
        "<!-- Generated by clients/cursor/generate.py from the skill the Claude Code plugin\n"
        "     ships, so both clients give the same guidance. Edit the skill, not this file. -->\n\n"
        f"{body}"
    )
    print(f"wrote {RULE.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
