"""A person who can sign in. The only table this template ships.

Two things it deliberately does not have:

* **No password column.** `hashed_password` holds an Argon2id digest, and there is no other
  representation of the password anywhere in the system — not encrypted, not reversible, not
  recoverable. The only operation is "does this input produce this digest".
* **No `last_login_at`.** A column written on every login turns the hottest path in the service
  into a row-locking write. It belongs in an audit event.

Do not give this model a `__repr__` or a `to_dict` that includes the digest. One
`logger.info("user", user=user)` puts password hashes in a log aggregator, where retention is
measured in years and the access control is not the one this table was designed for.
"""

from __future__ import annotations

from sqlalchemy import Boolean, String
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base, TimestampMixin, UUIDMixin


class User(Base, UUIDMixin, TimestampMixin):
    __tablename__ = "users"

    #: Stored already lower-cased and trimmed by the request schema, so a plain unique index is
    #: enough. An expression index on `lower(email)` is not reliably autogenerated, and
    #: `alembic check` then reports drift on every run until somebody stops believing it.
    #: 320 is the RFC's maximum length for an address.
    email: Mapped[str] = mapped_column(String(320), nullable=False, unique=True, index=True)
    #: Argon2id digests from pwdlib are around 97 characters. 60 is the *bcrypt* number, and a
    #: `String(60)` column truncates the digest silently — every login then fails to verify.
    hashed_password: Mapped[str] = mapped_column(String(255), nullable=False)
    #: A column, not a deletion. A user row is referenced by whatever this service grows next, so
    #: deactivating is the operation that will actually be needed.
    is_active: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default="true")
